vich_uploader:
    db_driver: orm

<<<<<<< HEAD
    #mappings:
    #    affaires:
    #        uri_prefix: /images/affaires
    #        upload_destination: '%kernel.project_dir%/public/images/affaires'
=======
    mappings:
        affaires:
            uri_prefix: /images/affaires
            upload_destination: '%kernel.project_dir%/public/images/affaires'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
>>>>>>> d625ba784199937d51b314efd7a888a7107a2f51
